apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  build:
    secrets:
      - STORAGE_URL
  environments:
    - name: investigation
      build:
        from: radix
  components:
    - name: flask
      dockerfileName: tests/openvds/Dockerfile
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: investigation
          resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 10
