apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  environments:
    - name: investigation
      build:
        from: radix
  components:
    - name: flask
      dockerfileName: tests/openvds/Dockerfile
      secrets:
        - STORAGE_URL
      ports:
        - name: http
          port: 5000
      publicPort: http
      environmentConfig:
        - environment: investigation
          monitoring: false
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 8
