name: CI-Azure

on:
  workflow_dispatch:
  #schedule:
    # Run at 15.52 UTC every day
  #  - cron: '52 15 * * *'

jobs:
  before_performance_tests:
    name: Before All Performance tests on Azure
    runs-on: ubuntu-latest
    environment: Test

    env:
      ENVIRONMENT: test
    steps:
      - uses: actions/checkout@v2

      - name: Set infrastructure parameters
        run: |
          echo "CONTAINER_REGISTRY=${{ secrets.SETUP_PREFIX }}0containerRegistry.azurecr.io" >> $GITHUB_ENV

      - name: Login to Docker Registry with Service Principal
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push performance image to Docker
        run: |
          tag=${{ env.CONTAINER_REGISTRY }}/playground/performance
          docker build -f tests/performance/Dockerfile -t $tag .
          docker push $tag

  performance_tests:
    # Note: job uses default resources. Setup from the main resource is used
    #
    # Service Principal should have access to Resource group and "push" privileges to the container registry
    #
    # The following secrets are required:
    # SETUP_PREFIX: prefix for all created resources
    # RESOURCE_GROUP : name of the resource group used for deployment
    # AZURE_CLIENT_ID : client (application) id of the Service principal
    # AZURE_CLIENT_SECRET : client secret of the Service Principal
    # AZURE_CREDENTIALS : {"clientId": "<>","clientSecret": "<>","subscriptionId": "<>","tenantId": "<>"}
    # STORAGE_ACCOUNT_KEY : key used to access storage
    # SIGN_KEY : string used for secure exchange of information between services
    name: Performance tests on Azure
    runs-on: ubuntu-latest
    environment: Test
    needs: [before_performance_tests]

    env:
      ENVIRONMENT: test
    strategy:
      max-parallel: 1
      matrix:
        include:
          - ilines: 10
            xlines: 9
            samples: 8
            duration: "10s"
            vus: 1

    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run tests
        uses: './.github/actions/run_performance_test'
        with:
          ilines_number: ${{ matrix.ilines }}
          xlines_number: ${{ matrix.xlines }}
          samples_number: ${{ matrix.samples }}
          vus: ${{ matrix.vus }}
          duration: ${{ matrix.duration }}
