name: javascript
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build oneseismic/emscripten image and library
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t oneseismic/emscripten --output type=local,dest=build -f javascript/emscripten.dockerfile .

      - name: Run setup
        working-directory: javascript
        run: npm install
      - name: Run tests
        working-directory: javascript
        env:
          NODE_PATH: ${{ github.workspace}}/build/wasm/
        run: npm run testnode
